middleware/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('latency/', views.time_latency, name='time_latency'),
    path('latency/<int:eid>', views.time_latency, name='time_latency'),
    path('api/v1/namespaces/_/actions/fib',
         views.serverless_call, name='function'),
    path('api/v1/namespaces/_/actions/pyfib',
         views.serverless_call, name='py_function'),

]

middleware/middleware/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

middleware/core/models.py
from django.db import models


# Create your models here.
class Node(models.Model):
    node_name = models.CharField("Node name", max_length=30)
    host_address = models.CharField("Host name", max_length=30)
    host_user = models.CharField("user Id", max_length=30, default="user331828")
    host_cpu = models.FloatField("Measured cpu", default=0)
    host_kf_cpu = models.FloatField("KF cpu", default=0)
    host_kf_cpu_variance = models.FloatField("KF Uncertainty cpu", default=0)

    host_ping = models.FloatField("Ping Value", default=0)
    host_kf_ping = models.FloatField("KF Ping Value", default=0)

    host_enabled = models.BooleanField("Enable host to forward calls", default=True)

    ip_address = models.GenericIPAddressField()
    recent_call = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.node_name


class Experiment(models.Model):
    name = models.CharField("Experiment name", max_length=255)
    description = models.TextField("Experiment description", max_length=255, blank=True)
    n_value = models.IntegerField("Fibonacci n Value", default=5)
    n_nodes = models.IntegerField("Number of enabled Nodes", default=2)
    thread_count = models.IntegerField("Number of thread", default=1)
    filter_enabled = models.BooleanField("Filter enabled/disabled", default=False)
    ping_enabled = models.BooleanField("Ping enabled/disabled", default=False)
    show_plot = models.BooleanField("Show/Hide plot", default=False)

    def __str__(self):
        return "{} [n={}, node={}]".format(self.name, self.n_value, self.n_nodes)


class NodeLogValue(models.Model):
    host_fra_cpu = models.FloatField("Measured cpu Frankfurt", default=0)
    host_fra_kf_cpu = models.FloatField("KF cpu Frankfurt", default=0)
    host_ire_cpu = models.FloatField("Measured cpu Ireland", default=0)
    host_ire_kf_cpu = models.FloatField("KF cpu Ireland", default=0)

    # ping data for logs
    host_fra_ping = models.FloatField("Measured ping Frankfurt", default=0)
    host_fra_kf_ping = models.FloatField("KF ping Frankfurt", default=0)
    host_ire_ping = models.FloatField("Measured ping Ireland", default=0)
    host_ire_kf_ping = models.FloatField("KF ping Ireland", default=0)


class RequestLog(models.Model):
    called_node = models.ForeignKey(Node, on_delete=models.CASCADE)
    called_function = models.CharField("Give function name", max_length=300)
    called_delay = models.FloatField("Function Latency")
    called_url = models.CharField("Url Called", max_length=150)
    called_method = models.CharField("Method", max_length=30, default="GET")
    called_filter = models.CharField("Prediction Type", max_length=30, default="linear")
    measured_cpu = models.FloatField("Measured cpu at call", default=0)
    pred_cpu = models.FloatField("KF cpu at call", default=0)
    pred_cpu_variance = models.FloatField("KF cpu Uncertainty at call", default=0)
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE, null=True)

    node_data = models.ManyToManyField(NodeLogValue, verbose_name="Nodes Data", blank=True)

    recent_call = models.DateTimeField(auto_now=True)
    reply_call = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} [{}]".format(self.called_function, self.called_node.node_name)

middleware/templates/base.html
{% load static %}
<html>
<head>
    <title>
        {% block title %}Base title{% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} This Bootsrap css is added to all pages {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">


</head>
<body>
<div class="container px-4">
    {% block content %}
        Body content
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

</body>
</html>

middleware/templates/home.html
{% extends 'base.html' %}
{% block content %}

    {% for experiment in experiments %}
        <div class="row mb-5">
            <div class="col ">
                <div class="card">
                    <div class="card-header">
                        {{ experiment.name }} | exp={{ experiment.id }}, thread={{ experiment.thread_count }} , n={{ experiment.n_value }}, nodes={{ experiment.n_nodes }}, filter={{ experiment.filter_enabled }}, dataset={{experiment.requestlog_set.count}}
                    </div>
                    <div class="card-body">
                        <div id="exp{{ experiment.id }}"></div>
                        <p class="card-text">{{ experiment.description }}</p>
                    </div>
                </div>
            </div>
            {% include "script.html" with experiment=experiment %}
        </div>
    {% endfor %}
{% endblock %}

middleware/templates/script.html
<script>
    Highcharts.getJSON(
        'latency/{{ experiment.id }}',
        function (data) {
            Highcharts.chart('exp{{ experiment.id }}', {
                chart: {
                    zoomType: 'x'
                },
                title: {
                    text: '{{ experiment.name }}'
                },
                subtitle: {
                    text: (document.ontouchstart === undefined ?
                            'Click and drag in the plot area to zoom in' : 'Pinch the chart to zoom in')
                        + '<br> <span class="text-danger">Avg-Latency:' + data['avg_delay'] + " sec</span>"
                        + '<br> <span class="text-info">Avg-Mes-CPU:' + data['avg_measured_cpu'] + " %</span>"
                        + '<br> <span class="text-success">Avg-Pred-CPU:' + data['avg_pred_cpu'] + " %</span>"
                },
                xAxis: {
                    type: 'datetime',
                    gridLineWidth: 1,
                },
                yAxis: [
                    { // Primary yAxis
                        title: {
                            text: 'Call Latency',
                            style: {
                                color: Highcharts.getOptions().colors[0]
                            }
                        },
                        opposite: false
                    },
                    {
                        title: {
                            text: 'CPU Measured',
                        },
                        opposite: true
                    },
                    {
                        title: {
                            text: 'CPU Prediction',
                            style: {
                                color: Highcharts.getOptions().colors[2]
                            }
                        },
                        opposite: true
                    },
                    {
                        title: {
                            text: 'Ping ',
                            style: {
                                color: Highcharts.getOptions().colors[3]
                            }
                        },
                        opposite: true
                    }
                    ],
                legend: {
                    enabled: true
                },
                plotOptions: {
                    area: {
                        fillColor: {
                            linearGradient: {
                                x1: 0,
                                y1: 0,
                                x2: 0,
                                y2: 1
                            },
                            stops: [
                                [0, Highcharts.color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')],
                                [1, Highcharts.color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                            ]
                        },
                        marker: {
                            radius: 2
                        },
                        lineWidth: 1,
                        states: {
                            hover: {
                                lineWidth: 1
                            }
                        },
                        threshold: null
                    }
                },

                series: [
                    {
                        type: 'area',
                        name: 'Call Latency',
                        yAxis: 0,
                        data: data['latency']
                    },
                    {
                        type: 'area',
                        name: 'CPU Measured',
                        yAxis: 2,
                        data: data['mes_cpu']
                    },
                    {
                        type: 'area',
                        name: 'CPU Prediction',
                        yAxis: 2,
                        data: data['pred_cpu']
                    },
                    {
                        type: 'area',
                        name: 'CPU Frankfurt',
                        yAxis: 2,
                        data: data['fra_cpu']
                    }, {
                        type: 'area',
                        name: 'CPU Ireland',
                        yAxis: 2,
                        data: data['ire_cpu']
                    }, {
                        type: 'area',
                        name: 'Predicted CPU Frankfurt',
                        yAxis: 2,
                        data: data['pred_fra_cpu']
                    }, {
                        type: 'area',
                        name: 'Predicted CPU Ireland',
                        yAxis: 2,
                        data: data['pred_ira_cpu']
                    },
                    {
                        type: 'area',
                        name: 'Ping Frankfurt',
                        yAxis: 3,
                        data: data['fra_ping']
                    },
                    {
                        type: 'area',
                        name: 'Ping Ireland',
                        yAxis: 3,
                        data: data['ire_ping']
                    }

                    ]
            });
        }
    );
</script>